const ROOT_URL = "https://ownedit.xyz";

export const minikitConfig = {
    accountAssociation: {
        "header": "eyJmaWQiOi0xLCJ0eXBlIjoiYXV0aCIsImtleSI6IjB4MzU4RDk4ZDkwQkIwM0YyZjRBZkNhMDFBNTc0MjAxOGYwRDBhYjBDMSJ9",
        "payload": "eyJkb21haW4iOiJvd25lZGl0Lnh5eiJ9",
        "signature": "AAAAAAAAAAAAAAAAyhG94Fl3s2MRZwKIYr4qFzl2yhEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiSCrVbLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAul7REO_bo9AFv8iC11NYrLu4WEIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASQ_-6NvAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAARfqIazPTHbdnZ8gVPRpszycrchEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAPhSELIcxQMC9He6VmhtIBncm2etAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABB91ZH6kGL2jJWdXqZ_qNohQgIUJRttpAEWpeyH0eGYl47z3x1zaH3bXJvHs7tskEx_BV-f8_cy1uklXtsHL8O3BwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSSZJI"
    },
    miniapp: {
        version: "1",
        name: "Owned IT",
        subtitle: "Stack sats, not subscriptions",
        description: "Crypto-native creator commerce. Get paid onchain without platform risk.",
        screenshotUrls: [`${ROOT_URL}/assets/dashboard_preview.png`],
        iconUrl: `${ROOT_URL}/assets/logo.png`,
        splashImageUrl: `${ROOT_URL}/assets/logo.png`,
        splashBackgroundColor: "#ffffff",
        homeUrl: ROOT_URL,
        webhookUrl: `${ROOT_URL}/api/webhook`,
        primaryCategory: "social",
        tags: ["commerce", "crypto", "creators"],
        heroImageUrl: `${ROOT_URL}/assets/logo.png`,
        tagline: "Own your audience.",
        ogTitle: "OWNED IT",
        ogDescription: "Sell your knowledge direct to your audience.",
        ogImageUrl: `${ROOT_URL}/assets/logo.png`,
    },
} as const;
